// Code generated by gobind. DO NOT EDIT.

// Java class mobinsapi.Mobinsapi is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java mobinsapi
package mobinsapi;

import go.Seq;

public abstract class Mobinsapi {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Mobinsapi() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native void auth(String user, String pass) throws Exception;
	public static native void autoValidate(String secret) throws Exception;
	public static native String coefficients(long id) throws Exception;
	public static native String exportCAS() throws Exception;
	public static native String grades(long id) throws Exception;
	public static native void importCAS(String tkn) throws Exception;
	public static native boolean isAuthenticated() throws Exception;
	public static native boolean isTokenNeeded();
	public static native long loadGroups() throws Exception;
	public static native void newCAS() throws Exception;
	public static native void triggerEmail() throws Exception;
	public static native void validate(String code) throws Exception;
}
