// GENERATED by scripts/fetch_association_logos.py.
// Do not edit by hand; re-run the script instead.

/// The logo each bundled asset under `assets/images/associations/` was
/// baked from, by association id. An association absent here falls back
/// to its initials, so a dead upstream URL costs no network call; one
/// whose logo has since moved falls back to the remote image, because a
/// baked file is only the normalised form of the URL it came from.
const Map<String, String> kBundledAssociationLogos = <String, String>{
  'aeir': 'https://aeir.insa-rennes.fr/images/club/AElR.png',
  'bear': 'https://aeir.insa-rennes.fr/images/club/Club%20BEAR.png',
  'biip': 'https://aeir.insa-rennes.fr/images/club/BIIP.png',
  'boom': 'https://aeir.insa-rennes.fr/images/club/Boom.png',
  'club-amour': 'https://aeir.insa-rennes.fr/images/club/Club%20Amour.png',
  'club-belote': 'https://aeir.insa-rennes.fr/images/club/Club%20Belote.png',
  'club-chill': 'https://aeir.insa-rennes.fr/images/club/Club%20Chill.png',
  'club-cine': 'https://aeir.insa-rennes.fr/images/club/Club%20Cin%C3%A9.png',
  'club-coiffure':
      'https://aeir.insa-rennes.fr/images/club/Club%20Coiffure.png',
  'club-dj': 'https://aeir.insa-rennes.fr/images/club/Club%20DJ.png',
  'club-echecs': 'https://aeir.insa-rennes.fr/images/club/Club%20Echecs.png',
  'club-musique': 'https://aeir.insa-rennes.fr/images/club/Club%20Musique.png',
  'club-photo-video':
      'https://aeir.insa-rennes.fr/images/club/Club%20Photo%26Vid%C3%A9os.png',
  'club-poker': 'https://aeir.insa-rennes.fr/images/club/Club%20Poker.png',
  'club-rap': 'https://aeir.insa-rennes.fr/images/club/Club%20Rap.png',
  'club-solex': 'https://aeir.insa-rennes.fr/images/club/Club%20Solex.png',
  'cuis-insa': 'https://aeir.insa-rennes.fr/images/club/Cuis\'INSA.png',
  'dataloss': 'https://aeir.insa-rennes.fr/images/club/Dataloss.png',
  'fanfarinsarrasin':
      'https://aeir.insa-rennes.fr/images/club/FanfarINSArrasin.png',
  'festival-oeil-glauque': 'https://aeir.insa-rennes.fr/images/club/FOG.png',
  'foyer': 'https://aeir.insa-rennes.fr/images/club/Foyer.png',
  'gala': 'https://aeir.insa-rennes.fr/images/club/Gala.png',
  'greensa-rennes': 'https://aeir.insa-rennes.fr/images/club/Green\'sa.png',
  'imagine-ca':
      'https://aeir.insa-rennes.fr/images/club/Imagine%20%C3%A7a%20!.png',
  'ins-amap': 'https://aeir.insa-rennes.fr/images/club/Ins\'Amap.png',
  'ins-arc-en-ciel':
      'https://aeir.insa-rennes.fr/images/club/Ins\'arc-en-ciel.png',
  'insa-coudbien':
      'https://aeir.insa-rennes.fr/images/club/%20INSA\'coudbien.png',
  'insa-talks': 'https://aeir.insa-rennes.fr/images/club/INSA%20Talks%20.png',
  'insaerien': 'https://aeir.insa-rennes.fr/images/club/Insa%C3%A9rien.png',
  'insakura': 'https://aeir.insa-rennes.fr/images/club/Insakura.png',
  'insalan': 'https://aeir.insa-rennes.fr/images/club/InsaLan.png',
  'insaroule': 'https://aeir.insa-rennes.fr/images/club/Insaroule.png',
  'insatisfaites':
      'https://aeir.insa-rennes.fr/images/club/Insatisfait.e.s.png',
  'inscape-game':
      'https://aeir.insa-rennes.fr/images/club/Ins\'cape%20game.png',
  'kfet': 'https://aeir.insa-rennes.fr/images/club/Kf%C3%AAt.png',
  'lab-insa': 'https://aeir.insa-rennes.fr/images/club/Lab\'INSA.png',
  'megaphone': 'https://aeir.insa-rennes.fr/images/club/M%C3%A9gaphone.png',
  'oenologie': 'https://aeir.insa-rennes.fr/images/club/Club%20Oenologie.png',
  'robotique': 'https://aeir.insa-rennes.fr/images/club/Club%20Robot.png',
  'rocknsolex': 'https://aeir.insa-rennes.fr/images/club/Rock\'N%20Solex.png',
  'solid-alim': 'https://aeir.insa-rennes.fr/images/club/Solidalim.png',
  'son-et-lumiere':
      'https://aeir.insa-rennes.fr/images/club/Son%20%26%20Lumi%C3%A8re.png',
  'un-des-sens': 'https://aeir.insa-rennes.fr/images/club/Un%20Des%20Sens.png',
  'vulgaris-action':
      'https://aeir.insa-rennes.fr/images/club/Vulgaris\'Action.png',
  'wei': 'https://aeir.insa-rennes.fr/images/club/WEI.png',
  'weipa': 'https://aeir.insa-rennes.fr/images/club/WEIPA.png',
};
